#####-----敌方颜色-----#####
enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true
use_roi: false

#####-----ROI-----#####
roi: 
  x: 0
  y: 0
  width: 640
  height: 640

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 20

#####-----aimer参数-----#####
yaw_offset: -2.5
pitch_offset: 3
comming_angle: 60
leaving_angle: 20
high_speed_delay_time: 0.1
low_speed_delay_time: 0.15
decision_speed: 3.0

#####-----工业相机参数-----#####
camera_name: "mindvision"
exposure_ms: 2
gamma: 0.5
vid_pid: "f622:d13a"

# camera_name: "hikrobot"
# exposure_ms: 3
# gain: 10.0
# vid_pid: "2bdf:0001"

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 相机内参矩阵和畸变系数（使用示例值，需要根据实际标定结果修改）
camera_matrix: [1295.4665175006589, 0, 655.71498478800618, 0, 1297.2591156991834, 506.21320670125334, 0, 0, 1]
distort_coeffs: [-0.48599095566724387, 0.23999516531343185, -0.00029018466701866776, -0.00083639963030895752, 0]

# 相机到云台的旋转矩阵和平移向量（使用示例值，需要根据实际标定结果修改）
R_camera2gimbal: [0.046736929626455238, -0.055211941324114208, 0.99738021884550865, -0.99881598162461238, -0.016078770676278314, 0.0459141370909011, 0.013501639172863072, -0.99834518813322415, -0.055898041744621867]
t_camera2gimbal: [0.27420934670256336, 0.0098763306562371159, 0.043798385984197351]
